# Generated by Django 2.2.5 on 2021-01-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larave_appl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='State_name',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
