# Generated by Django 2.2.5 on 2021-01-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larave_appl', '0002_auto_20210119_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_info',
            name='Bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='Branch_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='Branch_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='Emp_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='Emp_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='Phone_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='Region_head',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
