# Generated by Django 2.2.5 on 2021-01-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larave_appl', '0003_auto_20210119_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_info',
            name='Location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
