# Generated by Django 2.2.5 on 2021-01-19 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('larave_appl', '0004_employee_info_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('District_name', models.CharField(blank=True, max_length=10, null=True)),
                ('District_State', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='larave_appl.State')),
                ('District_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='larave_appl.City')),
            ],
        ),
        migrations.AddField(
            model_name='employee_info',
            name='District',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='larave_appl.District'),
        ),
    ]
