# Generated by Django 2.2.5 on 2021-01-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larave_appl', '0005_auto_20210119_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_info',
            name='Alternative_Phone_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
