# Generated by Django 2.2.5 on 2021-01-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larave_appl', '0006_employee_info_alternative_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_info',
            name='City_name',
        ),
        migrations.RemoveField(
            model_name='employee_info',
            name='District',
        ),
    ]
