# Generated by Django 2.2.5 on 2021-01-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larave_appl', '0007_auto_20210119_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_info',
            name='City_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee_info',
            name='District',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
