# Generated by Django 2.2.5 on 2021-01-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larave_appl', '0008_auto_20210119_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_info',
            old_name='Region_head',
            new_name='Cluster_head',
        ),
        migrations.AddField(
            model_name='employee_info',
            name='Team_leader',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
