# Generated by Django 2.2.5 on 2021-01-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larave_appl', '0009_auto_20210119_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_info',
            name='designation',
            field=models.CharField(blank=True, choices=[('Branch Manager', 'Branch Manager'), ('Teller', 'Teller'), ('Assistent', 'Assistent')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='grade',
            field=models.CharField(blank=True, choices=[('BM', 'BM'), ('ABM', 'ABM'), ('C', 'C'), ('D', 'D')], max_length=10, null=True),
        ),
    ]
